//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Magics/FX/Sources/Settings/Input/TestControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TestControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TestControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TestControls"",
    ""maps"": [
        {
            ""name"": ""TestMagic"",
            ""id"": ""1a776de9-8564-4c69-9b02-a638b1a03aa4"",
            ""actions"": [
                {
                    ""name"": ""ADS"",
                    ""type"": ""Button"",
                    ""id"": ""0a526fc0-2dc1-40c2-92b1-94ee4e127e65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3c8d5c42-8974-40f9-848d-66f1549d9cd7"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ADS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TestMagic
        m_TestMagic = asset.FindActionMap("TestMagic", throwIfNotFound: true);
        m_TestMagic_ADS = m_TestMagic.FindAction("ADS", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TestMagic
    private readonly InputActionMap m_TestMagic;
    private ITestMagicActions m_TestMagicActionsCallbackInterface;
    private readonly InputAction m_TestMagic_ADS;
    public struct TestMagicActions
    {
        private @TestControls m_Wrapper;
        public TestMagicActions(@TestControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ADS => m_Wrapper.m_TestMagic_ADS;
        public InputActionMap Get() { return m_Wrapper.m_TestMagic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TestMagicActions set) { return set.Get(); }
        public void SetCallbacks(ITestMagicActions instance)
        {
            if (m_Wrapper.m_TestMagicActionsCallbackInterface != null)
            {
                @ADS.started -= m_Wrapper.m_TestMagicActionsCallbackInterface.OnADS;
                @ADS.performed -= m_Wrapper.m_TestMagicActionsCallbackInterface.OnADS;
                @ADS.canceled -= m_Wrapper.m_TestMagicActionsCallbackInterface.OnADS;
            }
            m_Wrapper.m_TestMagicActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ADS.started += instance.OnADS;
                @ADS.performed += instance.OnADS;
                @ADS.canceled += instance.OnADS;
            }
        }
    }
    public TestMagicActions @TestMagic => new TestMagicActions(this);
    public interface ITestMagicActions
    {
        void OnADS(InputAction.CallbackContext context);
    }
}
