//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scenes/scene_GameClear/GameClearController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameClearController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameClearController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameClearController"",
    ""maps"": [
        {
            ""name"": ""GameClear"",
            ""id"": ""2e4ac71c-c42b-477c-8e98-272b52fbdb30"",
            ""actions"": [
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""b7403b2a-87c1-4192-8c17-12a46f30cbde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e1f8048a-fb9d-431b-beb0-4b39bb34237a"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameClear
        m_GameClear = asset.FindActionMap("GameClear", throwIfNotFound: true);
        m_GameClear_Enter = m_GameClear.FindAction("Enter", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameClear
    private readonly InputActionMap m_GameClear;
    private IGameClearActions m_GameClearActionsCallbackInterface;
    private readonly InputAction m_GameClear_Enter;
    public struct GameClearActions
    {
        private @GameClearController m_Wrapper;
        public GameClearActions(@GameClearController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Enter => m_Wrapper.m_GameClear_Enter;
        public InputActionMap Get() { return m_Wrapper.m_GameClear; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameClearActions set) { return set.Get(); }
        public void SetCallbacks(IGameClearActions instance)
        {
            if (m_Wrapper.m_GameClearActionsCallbackInterface != null)
            {
                @Enter.started -= m_Wrapper.m_GameClearActionsCallbackInterface.OnEnter;
                @Enter.performed -= m_Wrapper.m_GameClearActionsCallbackInterface.OnEnter;
                @Enter.canceled -= m_Wrapper.m_GameClearActionsCallbackInterface.OnEnter;
            }
            m_Wrapper.m_GameClearActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
            }
        }
    }
    public GameClearActions @GameClear => new GameClearActions(this);
    public interface IGameClearActions
    {
        void OnEnter(InputAction.CallbackContext context);
    }
}
